package main

type ladingBillInfo struct {
	Tdbh      string `json:"tdbh"`      // 1、提单编号
	TdbhWf    string `json:"tdbhWf"`    // 2、提单编号外方
	Tltdlx    string `json:"tltdlx"`    // 3、提单类型
	TltdlxWf  string `json:"tltdlxWf"`  // 4、提单类型外方
	Tyrmc     string `json:"tyrmc"`     // 5、托运人
	TyrmcWf   string `json:"tyrmcWf"`   // 6、托运人外方
	Tyrdh     string `json:"tyrdh"`     // 7、托运人联系电话
	TyrdhWf   string `json:"tyrdhWf"`   // 8、托运人联系电话外方
	Tyrdz     string `json:"tyrdz"`     // 9、托运人地址
	TyrdzWf   string `json:"tyrdzWf"`   // 10、托运人地址外方
	Shrhpzs   string `json:"shrhpzs"`   // 11、收货人
	ShrhpzsWf string `json:"shrhpzsWf"` // 12、收货人外方
	Shrlxdh   string `json:"shrlxdh"`   // 13、收货人联系电话
	ShrlxdhWf string `json:"shrlxdhWf"` // 14、收货人联系电话外方
	Shrdz     string `json:"shrdz"`     // 15、收货人地址
	ShrdzWf   string `json:"shrdzWf"`   // 16、收货人地址外方
	Tzrmc     string `json:"tzrmc"`     // 17、通知人
	TzrmcWf   string `json:"tzrmcWf"`   // 18、通知人外方
	Tzrdh     string `json:"tzrdh"`     // 19、通知人电话
	TzrdhWf   string `json:"tzrdhWf"`   // 20、通知人电话外方
	Tzrdz     string `json:"tzrdz"`     // 21、通知人地址
	TzrdzWf   string `json:"tzrdzWf"`   // 22、通知人地址外方
	Qdys      string `json:"qdys"`      // 23、前段运输
	QdysWf    string `json:"qdysWf"`    // 24、前段运输外方
	Shd       string `json:"shd"`       // 25、揽货地
	ShdWf     string `json:"shdWf"`     // 26、揽货地外方
	Zhg       string `json:"zhg"`       // 27、装货港/站
	ZhgWf     string `json:"zhgWf"`     // 28、装货港/站外方
	Cc        string `json:"cc"`        // 29、航次/车次/车号
	CcWf      string `json:"ccWf"`      // 30、航次/车次/车号外方
	Jfd       string `json:"jfd"`       // 31、交付地
	JfdWf     string `json:"jfdWf"`     // 32、交付地外方
	Xhg       string `json:"xhg"`       // 33、卸货港/站
	XhgWf     string `json:"xhgWf"`     // 34、卸货港/站外方
	Fy        string `json:"fy"`        // 35、运费及费用说明
	FyWf      string `json:"fyWf"`      // 36、运费及费用说明外方
	Thddl     string `json:"thddl"`     // 37、提货地代理
	ThddlWf   string `json:"thddlWf"`   // 38、提货地代理外方
	Zjs       string `json:"zjs"`       // 39、计算赔偿限制总件数
	ZjsWf     string `json:"zjsWf"`     // 40、计算赔偿限制总件数外方
	Qfdd      string `json:"qfdd"`      // 41、签发地点
	QfddWf    string `json:"qfddWf"`    // 42、签发地点外方
	Qfrq      string `json:"qfrq"`      // 43、签发日期
	QfrqWf    string `json:"qfrqWf"`    // 44、签发日期外方
	Qfrsm     string `json:"qfrsm"`     // 45、签发人声明
	QfrsmWf   string `json:"qfrsmWf"`   // 46、签发人声明外方
	Mthhm     string `json:"mthhm"`     // 47、唛头和号码
	Xh        string `json:"xh"`        // 48、箱号
	Jzx       string `json:"jzx"`       // 49、集装箱/包装数
	Hwms      string `json:"hwms"`      // 50、货物描述
	Mz        string `json:"mz"`        // 51、毛重
	Cm        string `json:"cm"`        // 52、尺码
	Fh        string `json:"fh"`        // 53、封号
	Ydhm      string `json:"ydhm"`      // 54、运单号码
	Sqrid     string `json:"sqrid"`     // 55、申请人(企业)代码
	Sqrmc     string `json:"sqrmc"`     // 56、申请人(企业)名称
	Sqrshxydm string `json:"sqrshxydm"` // 57、申请人(企业)社会信用代码
	Tdcyr     string `json:"tdcyr"`     // 58、持有人(企业)代码
	Tdcyrmc   string `json:"tdcyrmc"`   // 59、持有人(企业)名称
	Cyrshxydm string `json:"cyrshxydm"` // 60、持有人(企业)社会信用代码
	Qfdw      string `json:"qfdw"`      // 61、签发单位代码
	Qfdwmc    string `json:"qfdwmc"`    // 62、签发单位名称
	Qfrid     string `json:"qfrid"`     // 63、签发人代码
	Qfrmc     string `json:"qfrmc"`     // 64、签发人名称
	Ydlx      string `json:"ydlx"`      // 65、运单类型
}

type ladingBillCrossParams struct {
	CrossChainID           string         `json:"crossChainID"`           // 跨链唯一标识
	CorpHolderOrgCode      string         `json:"corpHolderOrgCode"`      // 持有企业组代号
	FinanceReceiverOrgCode string         `json:"financeReceiverOrgCode"` // 接收金融机构组代号
	LadingBillCR           ladingBillInfo `json:"ladingBillCR"`           // 提单信息
	Freeze                 bool           `json:"freeze"`                 // 是否被冻结
	Timestamp              int64          `json:"timestamp"`              // 时间戳
	Memo                   string         `json:"memo"`                   // 附言
}
